### ISSUE TITLE
discord bot

### ISSUE THREAD

**Issue by deveron87** [urbinek/discord-dm-boot#1]
[assistant.json](https://github.com/urbinek/discord-dm-boot/files/14547426/assistant.json)
[README.md](https://github.com/urbinek/discord-dm-boot/files/14547427/README.md)
[requirements.txt](https://github.com/urbinek/discord-dm-boot/files/14547428/requirements.txt)
[session.json](https://github.com/urbinek/discord-dm-boot/files/14547429/session.json)
[session_log.json](https://github.com/urbinek/discord-dm-boot/files/14547431/session_log.json)

kiedy startowałem bota z visuala wydaje mi sie ze docker nie był odpalony. plik session.json był pusty

**Comment by deveron87** [comment]
PS D:\dm bot\discord-dm-boot-main> docker compose --file ./docker-compose.yml up
[+] Running 1/0
 ✔ Container discord-dm-boot-main-disco-bot-1  Created                                                                                                          0.0s 
Attaching to disco-bot-1
disco-bot-1  | 2024-03-09 18:49:40 WARNING  PyNaCl is not installed, voice will NOT be supported
disco-bot-1  | 2024-03-09 18:49:40 INFO     HTTP Request: POST https://api.openai.com/v1/assistants "HTTP/1.1 200 OK"
disco-bot-1  | 2024-03-09 18:49:40 INFO     HTTP Request: POST https://api.openai.com/v1/threads "HTTP/1.1 200 OK"
disco-bot-1  | Traceback (most recent call last):
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 202, in <module>
disco-bot-1  |     disco_dm()
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 107, in disco_dm
disco-bot-1  |     update_session(assistant_id, thread_id)
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 40, in update_session
disco-bot-1  |     session_data = load_session()
disco-bot-1  |                    ^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 31, in load_session
disco-bot-1  |     return json.load(f)
disco-bot-1  |            ^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
disco-bot-1  |     return loads(fp.read(),
disco-bot-1  |            ^^^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
disco-bot-1  |     return _default_decoder.decode(s)
disco-bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
disco-bot-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
disco-bot-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
disco-bot-1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
disco-bot-1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
disco-bot-1 exited with code 1
disco-bot-1  | 2024-03-09 18:49:42 WARNING  PyNaCl is not installed, voice will NOT be supported
disco-bot-1  | 2024-03-09 18:49:42 INFO     HTTP Request: POST https://api.openai.com/v1/assistants "HTTP/1.1 200 OK"
disco-bot-1  | 2024-03-09 18:49:42 INFO     HTTP Request: POST https://api.openai.com/v1/threads "HTTP/1.1 200 OK"
disco-bot-1  | Traceback (most recent call last):
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 202, in <module>
disco-bot-1  |     disco_dm()
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 107, in disco_dm
disco-bot-1  |     update_session(assistant_id, thread_id)
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 40, in update_session
disco-bot-1  |     session_data = load_session()
disco-bot-1  |                    ^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/src/app/./disco-bot.py", line 31, in load_session
disco-bot-1  |     return json.load(f)
disco-bot-1  |            ^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/__init__.py", line 293, in load
disco-bot-1  |     return loads(fp.read(),
disco-bot-1  |            ^^^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
disco-bot-1  |     return _default_decoder.decode(s)
disco-bot-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
disco-bot-1  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
disco-bot-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
disco-bot-1  |   File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
disco-bot-1  |     raise JSONDecodeError("Expecting value", s, err.value) from None
disco-bot-1  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
disco-bot-1 exited with code 1
